# Generated by Django 2.1.1 on 2019-08-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interest',
            name='sources',
            field=models.TextField(default=''),
        ),
    ]
